uint64 timestamp		# time since system start (microseconds)

uint64  event_utc_time		# The io port of unicore detects the utc time when the event is triggered (eg: the io port of the unicore is triggered when the camera takes a photo)
float64 lat		# The io port of unicore detects the lat when the event is triggered
float64 lon		# The io port of unicore detects the lon time when the event is triggered
float64 hgt 	# The io port of unicore detects the hgt time when the event is triggered
